# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Fri May  6 13:31:17 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 660)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_inputFileLito = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputFileLito.setObjectName("lineEdit_inputFileLito")
        self.gridLayout.addWidget(self.lineEdit_inputFileLito, 2, 1, 1, 1)
        self.pushButton_inputFileLito = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFileLito.setObjectName("pushButton_inputFileLito")
        self.gridLayout.addWidget(self.pushButton_inputFileLito, 2, 2, 1, 2)
        self.pushButton_inputFileLimit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFileLimit.setObjectName("pushButton_inputFileLimit")
        self.gridLayout.addWidget(self.pushButton_inputFileLimit, 3, 2, 1, 2)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.gridLayout.addWidget(self.pushButton_outputDir, 5, 2, 1, 2)
        self.pushButton_OK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout.addWidget(self.pushButton_OK, 8, 2, 1, 1)
        self.plainTextEdit_features = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_features.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_features.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit_features.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_features.setOverwriteMode(False)
        self.plainTextEdit_features.setTabStopWidth(80)
        self.plainTextEdit_features.setTabStopDistance(80.0)
        self.plainTextEdit_features.setObjectName("plainTextEdit_features")
        self.gridLayout.addWidget(self.plainTextEdit_features, 1, 1, 1, 1)
        self.pushButton_inputFilesFeatures = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFilesFeatures.setObjectName("pushButton_inputFilesFeatures")
        self.gridLayout.addWidget(self.pushButton_inputFilesFeatures, 1, 2, 1, 2)
        self.label_inputLito = QtWidgets.QLabel(self.centralwidget)
        self.label_inputLito.setObjectName("label_inputLito")
        self.gridLayout.addWidget(self.label_inputLito, 2, 0, 1, 1)
        self.label_inputLimit = QtWidgets.QLabel(self.centralwidget)
        self.label_inputLimit.setObjectName("label_inputLimit")
        self.gridLayout.addWidget(self.label_inputLimit, 3, 0, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 8, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(575, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.label_inputFeatures = QtWidgets.QLabel(self.centralwidget)
        self.label_inputFeatures.setObjectName("label_inputFeatures")
        self.gridLayout.addWidget(self.label_inputFeatures, 1, 0, 1, 1)
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setObjectName("label_output")
        self.gridLayout.addWidget(self.label_output, 5, 0, 1, 1)
        self.lineEdit_inputFileLimit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputFileLimit.setObjectName("lineEdit_inputFileLimit")
        self.gridLayout.addWidget(self.lineEdit_inputFileLimit, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        self.lineEdit_outputDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outputDir.setObjectName("lineEdit_outputDir")
        self.gridLayout.addWidget(self.lineEdit_outputDir, 5, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Options = QtWidgets.QWidget()
        self.tab_Options.setAutoFillBackground(True)
        self.tab_Options.setObjectName("tab_Options")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Options)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_fieldName = QtWidgets.QLabel(self.tab_Options)
        self.label_fieldName.setObjectName("label_fieldName")
        self.gridLayout_2.addWidget(self.label_fieldName, 0, 1, 1, 1)
        self.comboBox_fieldName = QtWidgets.QComboBox(self.tab_Options)
        self.comboBox_fieldName.setObjectName("comboBox_fieldName")
        self.gridLayout_2.addWidget(self.comboBox_fieldName, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(268, 24, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.label_id = QtWidgets.QLabel(self.tab_Options)
        self.label_id.setObjectName("label_id")
        self.gridLayout_2.addWidget(self.label_id, 1, 1, 1, 1)
        self.comboBox_id = QtWidgets.QComboBox(self.tab_Options)
        self.comboBox_id.setObjectName("comboBox_id")
        self.gridLayout_2.addWidget(self.comboBox_id, 1, 2, 1, 1)
        self.label_atLeast = QtWidgets.QLabel(self.tab_Options)
        self.label_atLeast.setObjectName("label_atLeast")
        self.gridLayout_2.addWidget(self.label_atLeast, 2, 1, 1, 1)
        self.lineEdit_atLeast = QtWidgets.QLineEdit(self.tab_Options)
        self.lineEdit_atLeast.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_atLeast.setInputMask("")
        self.lineEdit_atLeast.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_atLeast.setObjectName("lineEdit_atLeast")
        self.gridLayout_2.addWidget(self.lineEdit_atLeast, 2, 2, 1, 1)
        self.label_maxSamples = QtWidgets.QLabel(self.tab_Options)
        self.label_maxSamples.setObjectName("label_maxSamples")
        self.gridLayout_2.addWidget(self.label_maxSamples, 3, 1, 1, 1)
        self.lineEdit_maxSamples = QtWidgets.QLineEdit(self.tab_Options)
        self.lineEdit_maxSamples.setInputMask("")
        self.lineEdit_maxSamples.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxSamples.setObjectName("lineEdit_maxSamples")
        self.gridLayout_2.addWidget(self.lineEdit_maxSamples, 3, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab_Options)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 4, 1, 1, 2)
        self.label_useCoordinates = QtWidgets.QLabel(self.tab_Options)
        self.label_useCoordinates.setObjectName("label_useCoordinates")
        self.gridLayout_2.addWidget(self.label_useCoordinates, 5, 1, 1, 1)
        self.checkBox_coords = QtWidgets.QCheckBox(self.tab_Options)
        self.checkBox_coords.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_coords.setText("")
        self.checkBox_coords.setChecked(False)
        self.checkBox_coords.setObjectName("checkBox_coords")
        self.gridLayout_2.addWidget(self.checkBox_coords, 5, 2, 1, 1)
        self.label_useCartesianProd = QtWidgets.QLabel(self.tab_Options)
        self.label_useCartesianProd.setObjectName("label_useCartesianProd")
        self.gridLayout_2.addWidget(self.label_useCartesianProd, 6, 1, 1, 1)
        self.checkBox_cartesianProd = QtWidgets.QCheckBox(self.tab_Options)
        self.checkBox_cartesianProd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_cartesianProd.setText("")
        self.checkBox_cartesianProd.setObjectName("checkBox_cartesianProd")
        self.gridLayout_2.addWidget(self.checkBox_cartesianProd, 6, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.tab_Options)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 7, 1, 1, 2)
        self.label_runPCA = QtWidgets.QLabel(self.tab_Options)
        self.label_runPCA.setCursor(QtCore.Qt.ArrowCursor)
        self.label_runPCA.setObjectName("label_runPCA")
        self.gridLayout_2.addWidget(self.label_runPCA, 8, 1, 1, 1)
        self.checkBox_PCA = QtWidgets.QCheckBox(self.tab_Options)
        self.checkBox_PCA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_PCA.setText("")
        self.checkBox_PCA.setChecked(True)
        self.checkBox_PCA.setObjectName("checkBox_PCA")
        self.gridLayout_2.addWidget(self.checkBox_PCA, 8, 2, 1, 1)
        self.label_PCAPercent = QtWidgets.QLabel(self.tab_Options)
        self.label_PCAPercent.setObjectName("label_PCAPercent")
        self.gridLayout_2.addWidget(self.label_PCAPercent, 9, 1, 1, 1)
        self.comboBox_PCAPercent = QtWidgets.QComboBox(self.tab_Options)
        self.comboBox_PCAPercent.setAutoFillBackground(False)
        self.comboBox_PCAPercent.setMaxVisibleItems(10)
        self.comboBox_PCAPercent.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_PCAPercent.setObjectName("comboBox_PCAPercent")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_PCAPercent, 9, 2, 1, 1)
        self.tabWidget.addTab(self.tab_Options, "")
        self.tab_Advanced = QtWidgets.QWidget()
        self.tab_Advanced.setAutoFillBackground(True)
        self.tab_Advanced.setObjectName("tab_Advanced")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_Advanced)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_seed = QtWidgets.QLineEdit(self.tab_Advanced)
        self.lineEdit_seed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_seed.setInputMask("")
        self.lineEdit_seed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_seed.setObjectName("lineEdit_seed")
        self.gridLayout_3.addWidget(self.lineEdit_seed, 0, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 2, 2, 1, 1)
        self.label_randomSeed = QtWidgets.QLabel(self.tab_Advanced)
        self.label_randomSeed.setObjectName("label_randomSeed")
        self.gridLayout_3.addWidget(self.label_randomSeed, 0, 1, 1, 2)
        self.comboBox_numberOfRealizations = QtWidgets.QComboBox(self.tab_Advanced)
        self.comboBox_numberOfRealizations.setObjectName("comboBox_numberOfRealizations")
        self.comboBox_numberOfRealizations.addItem("")
        self.comboBox_numberOfRealizations.addItem("")
        self.comboBox_numberOfRealizations.addItem("")
        self.comboBox_numberOfRealizations.addItem("")
        self.comboBox_numberOfRealizations.addItem("")
        self.comboBox_numberOfRealizations.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_numberOfRealizations, 1, 3, 1, 1)
        self.label_numberOfRealizations = QtWidgets.QLabel(self.tab_Advanced)
        self.label_numberOfRealizations.setObjectName("label_numberOfRealizations")
        self.gridLayout_3.addWidget(self.label_numberOfRealizations, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Advanced, "")
        self.gridLayout.addWidget(self.tabWidget, 7, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_PCAPercent.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_inputFileLito.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select vector (target) files.", None, -1))
        self.pushButton_inputFileLito.setText(QtWidgets.QApplication.translate("MainWindow", "Select file", None, -1))
        self.pushButton_inputFileLimit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select vector (area of interest) files.", None, -1))
        self.pushButton_inputFileLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Select file", None, -1))
        self.pushButton_outputDir.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select output directory.", None, -1))
        self.pushButton_outputDir.setText(QtWidgets.QApplication.translate("MainWindow", "Select folder", None, -1))
        self.pushButton_OK.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to run the program.", None, -1))
        self.pushButton_OK.setText(QtWidgets.QApplication.translate("MainWindow", "OK", None, -1))
        self.pushButton_inputFilesFeatures.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select raster (feature) files.", None, -1))
        self.pushButton_inputFilesFeatures.setText(QtWidgets.QApplication.translate("MainWindow", "Select files", None, -1))
        self.label_inputLito.setText(QtWidgets.QApplication.translate("MainWindow", "Vector (target):", None, -1))
        self.label_inputLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Boundary:", None, -1))
        self.pushButton_Cancel.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.label_inputFeatures.setText(QtWidgets.QApplication.translate("MainWindow", "Rasters (features):", None, -1))
        self.label_output.setText(QtWidgets.QApplication.translate("MainWindow", "Output Folder:", None, -1))
        self.label_fieldName.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The name of the field that contains the classes to be predicted (e.g., geology).", None, -1))
        self.label_fieldName.setText(QtWidgets.QApplication.translate("MainWindow", "Target field name:", None, -1))
        self.comboBox_fieldName.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The name of the field that contains the classes to be predicted (e.g., geology)", None, -1))
        self.label_id.setToolTip(QtWidgets.QApplication.translate("MainWindow", "A unique feature identifier (e.g., row number)", None, -1))
        self.label_id.setText(QtWidgets.QApplication.translate("MainWindow", "Feature ID (fiducial):", None, -1))
        self.comboBox_id.setToolTip(QtWidgets.QApplication.translate("MainWindow", "A unique feature identifier (e.g., row number)", None, -1))
        self.label_atLeast.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classes with fewer samples than what is marked here will be discarded.", None, -1))
        self.label_atLeast.setText(QtWidgets.QApplication.translate("MainWindow", "Minimum number of samples per class:", None, -1))
        self.lineEdit_atLeast.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with fewer samples than the number indicated here will be discarded.", None, -1))
        self.lineEdit_atLeast.setText(QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.label_maxSamples.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with more samples than the number indicated here will be randomly selected.", None, -1))
        self.label_maxSamples.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum number of samples per class:", None, -1))
        self.lineEdit_maxSamples.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with more samples than the number indicated here will be randomly selected.", None, -1))
        self.lineEdit_maxSamples.setText(QtWidgets.QApplication.translate("MainWindow", "150", None, -1))
        self.label_useCoordinates.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use the rasters coordinates as predictors in the model (increases model\'s spatial awareness)", None, -1))
        self.label_useCoordinates.setText(QtWidgets.QApplication.translate("MainWindow", "Use coordinates as features?", None, -1))
        self.checkBox_coords.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Check for \"yes\"", None, -1))
        self.label_useCartesianProd.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Calculate the product of the rasters coordinates (creates \"X*X\", \"X*Y\", and \"Y*Y\" synthetic features from the coordinates) and use as predictors in the model (increases model\'s spatial awareness)", None, -1))
        self.label_useCartesianProd.setText(QtWidgets.QApplication.translate("MainWindow", "Use coordinate products as features?", None, -1))
        self.checkBox_cartesianProd.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Check for \"yes\"", None, -1))
        self.label_runPCA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Multi-band rasters (e.g., Landsat images) might have a high correlation. The program can automatically reduce the dimensionality of such inputs.", None, -1))
        self.label_runPCA.setText(QtWidgets.QApplication.translate("MainWindow", "Use PCA to reduce dimensionality of multi-band rasters?", None, -1))
        self.checkBox_PCA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Check for \"yes\"", None, -1))
        self.label_PCAPercent.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The Principal Components are organized based on the amount of variance they explain. You can select how much variance the program will keep. Selecting a percentage equals to 100 means the program only rotates the data and does not remove any of its variance. ", None, -1))
        self.label_PCAPercent.setText(QtWidgets.QApplication.translate("MainWindow", "Select percentage of the variance to keep:", None, -1))
        self.comboBox_PCAPercent.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select the desired percentage of variance to keep. ", None, -1))
        self.comboBox_PCAPercent.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "95", None, -1))
        self.comboBox_PCAPercent.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "99", None, -1))
        self.comboBox_PCAPercent.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "95", None, -1))
        self.comboBox_PCAPercent.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "90", None, -1))
        self.comboBox_PCAPercent.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "80", None, -1))
        self.comboBox_PCAPercent.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "70", None, -1))
        self.comboBox_PCAPercent.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "50", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Options), QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.lineEdit_seed.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Keep the same number for reproducibility; change the number to generate different realizations of the same model.", None, -1))
        self.lineEdit_seed.setText(QtWidgets.QApplication.translate("MainWindow", "123456789", None, -1))
        self.label_randomSeed.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Seed for the pseudo-number generator.", None, -1))
        self.label_randomSeed.setText(QtWidgets.QApplication.translate("MainWindow", "Random seed:", None, -1))
        self.comboBox_numberOfRealizations.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Number of realizations (experiments with the same hyperparameters, different random seeds).", None, -1))
        self.comboBox_numberOfRealizations.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "1", None, -1))
        self.comboBox_numberOfRealizations.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "5", None, -1))
        self.comboBox_numberOfRealizations.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "10", None, -1))
        self.comboBox_numberOfRealizations.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "20", None, -1))
        self.comboBox_numberOfRealizations.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "50", None, -1))
        self.comboBox_numberOfRealizations.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "100", None, -1))
        self.label_numberOfRealizations.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select more than one realization to repeat the experiments with different random seeds.", None, -1))
        self.label_numberOfRealizations.setText(QtWidgets.QApplication.translate("MainWindow", "Number of realizations", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Advanced), QtWidgets.QApplication.translate("MainWindow", "Advanced", None, -1))

