# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui',
# licensing of 'MainWindow.ui' applies.
#
# Created: Fri Apr  8 10:38:53 2022
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_inputFileLito = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputFileLito.setObjectName("lineEdit_inputFileLito")
        self.gridLayout.addWidget(self.lineEdit_inputFileLito, 2, 1, 1, 1)
        self.pushButton_inputFileLito = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFileLito.setObjectName("pushButton_inputFileLito")
        self.gridLayout.addWidget(self.pushButton_inputFileLito, 2, 2, 1, 2)
        self.plainTextEdit_features = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_features.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_features.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit_features.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.plainTextEdit_features.setOverwriteMode(False)
        self.plainTextEdit_features.setTabStopWidth(80)
        self.plainTextEdit_features.setTabStopDistance(80.0)
        self.plainTextEdit_features.setObjectName("plainTextEdit_features")
        self.gridLayout.addWidget(self.plainTextEdit_features, 1, 1, 1, 1)
        self.pushButton_inputFileLimit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFileLimit.setObjectName("pushButton_inputFileLimit")
        self.gridLayout.addWidget(self.pushButton_inputFileLimit, 3, 2, 1, 2)
        self.pushButton_outputDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_outputDir.setObjectName("pushButton_outputDir")
        self.gridLayout.addWidget(self.pushButton_outputDir, 5, 2, 1, 2)
        self.pushButton_OK = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OK.setObjectName("pushButton_OK")
        self.gridLayout.addWidget(self.pushButton_OK, 8, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(575, 27, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 8, 0, 1, 2)
        self.pushButton_inputFilesFeatures = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputFilesFeatures.setObjectName("pushButton_inputFilesFeatures")
        self.gridLayout.addWidget(self.pushButton_inputFilesFeatures, 1, 2, 1, 2)
        self.label_inputLito = QtWidgets.QLabel(self.centralwidget)
        self.label_inputLito.setObjectName("label_inputLito")
        self.gridLayout.addWidget(self.label_inputLito, 2, 0, 1, 1)
        self.label_inputLimit = QtWidgets.QLabel(self.centralwidget)
        self.label_inputLimit.setObjectName("label_inputLimit")
        self.gridLayout.addWidget(self.label_inputLimit, 3, 0, 1, 1)
        self.pushButton_Cancel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.gridLayout.addWidget(self.pushButton_Cancel, 8, 3, 1, 1)
        self.lineEdit_inputFileLimit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inputFileLimit.setObjectName("lineEdit_inputFileLimit")
        self.gridLayout.addWidget(self.lineEdit_inputFileLimit, 3, 1, 1, 1)
        self.lineEdit_outputDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_outputDir.setObjectName("lineEdit_outputDir")
        self.gridLayout.addWidget(self.lineEdit_outputDir, 5, 1, 1, 1)
        self.label_inputFeatures = QtWidgets.QLabel(self.centralwidget)
        self.label_inputFeatures.setObjectName("label_inputFeatures")
        self.gridLayout.addWidget(self.label_inputFeatures, 1, 0, 1, 1)
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setObjectName("label_output")
        self.gridLayout.addWidget(self.label_output, 5, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        self.groupBox_options = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_options.setObjectName("groupBox_options")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_options)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_atLeast = QtWidgets.QLineEdit(self.groupBox_options)
        self.lineEdit_atLeast.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_atLeast.setInputMask("")
        self.lineEdit_atLeast.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_atLeast.setObjectName("lineEdit_atLeast")
        self.gridLayout_2.addWidget(self.lineEdit_atLeast, 2, 2, 1, 1)
        self.label_atLeast = QtWidgets.QLabel(self.groupBox_options)
        self.label_atLeast.setObjectName("label_atLeast")
        self.gridLayout_2.addWidget(self.label_atLeast, 2, 1, 1, 1)
        self.lineEdit_maxSamples = QtWidgets.QLineEdit(self.groupBox_options)
        self.lineEdit_maxSamples.setInputMask("")
        self.lineEdit_maxSamples.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxSamples.setObjectName("lineEdit_maxSamples")
        self.gridLayout_2.addWidget(self.lineEdit_maxSamples, 3, 2, 1, 1)
        self.label_fieldName = QtWidgets.QLabel(self.groupBox_options)
        self.label_fieldName.setObjectName("label_fieldName")
        self.gridLayout_2.addWidget(self.label_fieldName, 0, 1, 1, 1)
        self.label_maxSamples = QtWidgets.QLabel(self.groupBox_options)
        self.label_maxSamples.setObjectName("label_maxSamples")
        self.gridLayout_2.addWidget(self.label_maxSamples, 3, 1, 1, 1)
        self.comboBox_fieldName = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_fieldName.setObjectName("comboBox_fieldName")
        self.gridLayout_2.addWidget(self.comboBox_fieldName, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.checkBox_coords = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_coords.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_coords.setText("")
        self.checkBox_coords.setChecked(False)
        self.checkBox_coords.setObjectName("checkBox_coords")
        self.gridLayout_2.addWidget(self.checkBox_coords, 5, 2, 1, 1)
        self.label_id = QtWidgets.QLabel(self.groupBox_options)
        self.label_id.setObjectName("label_id")
        self.gridLayout_2.addWidget(self.label_id, 1, 1, 1, 1)
        self.comboBox_id = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_id.setObjectName("comboBox_id")
        self.gridLayout_2.addWidget(self.comboBox_id, 1, 2, 1, 1)
        self.label_useCoordinates = QtWidgets.QLabel(self.groupBox_options)
        self.label_useCoordinates.setObjectName("label_useCoordinates")
        self.gridLayout_2.addWidget(self.label_useCoordinates, 5, 1, 1, 1)
        self.checkBox_PCA = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_PCA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_PCA.setText("")
        self.checkBox_PCA.setChecked(True)
        self.checkBox_PCA.setObjectName("checkBox_PCA")
        self.gridLayout_2.addWidget(self.checkBox_PCA, 7, 2, 1, 1)
        self.label_runPCA = QtWidgets.QLabel(self.groupBox_options)
        self.label_runPCA.setCursor(QtCore.Qt.ArrowCursor)
        self.label_runPCA.setObjectName("label_runPCA")
        self.gridLayout_2.addWidget(self.label_runPCA, 7, 1, 1, 1)
        self.label_PCAPercent = QtWidgets.QLabel(self.groupBox_options)
        self.label_PCAPercent.setObjectName("label_PCAPercent")
        self.gridLayout_2.addWidget(self.label_PCAPercent, 9, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_options)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 1, 1, 2)
        self.comboBox_PCAPercent = QtWidgets.QComboBox(self.groupBox_options)
        self.comboBox_PCAPercent.setAutoFillBackground(False)
        self.comboBox_PCAPercent.setMaxVisibleItems(10)
        self.comboBox_PCAPercent.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox_PCAPercent.setObjectName("comboBox_PCAPercent")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.comboBox_PCAPercent.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_PCAPercent, 9, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 7, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 820, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_PCAPercent.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.pushButton_inputFileLito.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select vector (target) files.", None, -1))
        self.pushButton_inputFileLito.setText(QtWidgets.QApplication.translate("MainWindow", "Select file", None, -1))
        self.pushButton_inputFileLimit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select vector (area of interest) files.", None, -1))
        self.pushButton_inputFileLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Select file", None, -1))
        self.pushButton_outputDir.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select output directory.", None, -1))
        self.pushButton_outputDir.setText(QtWidgets.QApplication.translate("MainWindow", "Select folder", None, -1))
        self.pushButton_OK.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to run the program.", None, -1))
        self.pushButton_OK.setText(QtWidgets.QApplication.translate("MainWindow", "OK", None, -1))
        self.pushButton_inputFilesFeatures.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Click to select raster (feature) files.", None, -1))
        self.pushButton_inputFilesFeatures.setText(QtWidgets.QApplication.translate("MainWindow", "Select files", None, -1))
        self.label_inputLito.setText(QtWidgets.QApplication.translate("MainWindow", "Vector (target):", None, -1))
        self.label_inputLimit.setText(QtWidgets.QApplication.translate("MainWindow", "Boundary:", None, -1))
        self.pushButton_Cancel.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.label_inputFeatures.setText(QtWidgets.QApplication.translate("MainWindow", "Rasters (features):", None, -1))
        self.label_output.setText(QtWidgets.QApplication.translate("MainWindow", "Output Folder:", None, -1))
        self.groupBox_options.setTitle(QtWidgets.QApplication.translate("MainWindow", "Options", None, -1))
        self.lineEdit_atLeast.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with fewer samples than the number indicated here will be discarded.", None, -1))
        self.lineEdit_atLeast.setText(QtWidgets.QApplication.translate("MainWindow", "40", None, -1))
        self.label_atLeast.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classes with fewer samples than what is marked here will be discarded.", None, -1))
        self.label_atLeast.setText(QtWidgets.QApplication.translate("MainWindow", "Minimum number of samples per class:", None, -1))
        self.lineEdit_maxSamples.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with more samples than the number indicated here will be randomly selected.", None, -1))
        self.lineEdit_maxSamples.setText(QtWidgets.QApplication.translate("MainWindow", "150", None, -1))
        self.label_fieldName.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The name of the field that contains the classes to be predicted (e.g., geology).", None, -1))
        self.label_fieldName.setText(QtWidgets.QApplication.translate("MainWindow", "Target field name:", None, -1))
        self.label_maxSamples.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Classses with more samples than the number indicated here will be randomly selected.", None, -1))
        self.label_maxSamples.setText(QtWidgets.QApplication.translate("MainWindow", "Maximum number of samples per class:", None, -1))
        self.comboBox_fieldName.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The name of the field that contains the classes to be predicted (e.g., geology)", None, -1))
        self.checkBox_coords.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Check for \"yes\"", None, -1))
        self.label_id.setToolTip(QtWidgets.QApplication.translate("MainWindow", "A unique feature identifier (e.g., row number)", None, -1))
        self.label_id.setText(QtWidgets.QApplication.translate("MainWindow", "Feature ID (fiducial)", None, -1))
        self.comboBox_id.setToolTip(QtWidgets.QApplication.translate("MainWindow", "A unique feature identifier (e.g., row number)", None, -1))
        self.label_useCoordinates.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Use the rasters coordinates as predictors in the model (increases model\'s spatial awareness)", None, -1))
        self.label_useCoordinates.setText(QtWidgets.QApplication.translate("MainWindow", "Use coordinates as features?", None, -1))
        self.checkBox_PCA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Check for \"yes\"", None, -1))
        self.label_runPCA.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Multi-band rasters (e.g., Landsat images) might have a high correlation. The program can automatically reduce the dimensionality of such inputs.", None, -1))
        self.label_runPCA.setText(QtWidgets.QApplication.translate("MainWindow", "Use PCA to reduce dimensionality of multi-band rasters?", None, -1))
        self.label_PCAPercent.setToolTip(QtWidgets.QApplication.translate("MainWindow", "The Principal Components are organized based on the amount of variance they explain. You can select how much variance the program will keep. Selecting a percentage equals to 100 means the program only rotates the data and does not remove any of its variance. ", None, -1))
        self.label_PCAPercent.setText(QtWidgets.QApplication.translate("MainWindow", "Select percentage of the variance to keep:", None, -1))
        self.comboBox_PCAPercent.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Select the desired percentage of variance to keep. ", None, -1))
        self.comboBox_PCAPercent.setCurrentText(QtWidgets.QApplication.translate("MainWindow", "95", None, -1))
        self.comboBox_PCAPercent.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "99", None, -1))
        self.comboBox_PCAPercent.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "95", None, -1))
        self.comboBox_PCAPercent.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "90", None, -1))
        self.comboBox_PCAPercent.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "80", None, -1))
        self.comboBox_PCAPercent.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "70", None, -1))
        self.comboBox_PCAPercent.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "50", None, -1))

